name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  video_player: ^2.8.1
  # ML dependencies
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  camera: ^0.10.5+9
  get: ^4.7.2
  # system information
  device_info_plus: ^11.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/videos/
    - assets/images/
    - assets/instructions/
    - assets/models/
